apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}
  labels:
    {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["list", "watch"]
  {{/* Our controller needs permission to add the ServiceAccounts from the user to the -agent-mock CRB */}}
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["update"]
    resourceNames: [{{ template "newrelic-infra-operator.fullname" . }}-agent-mock]
---
{{/* agent-mock is the ClusterRole to be used by the injected agents to get metrics */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}-agent-mock
  labels: {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/proxy"
      - "pods"
      - "services"
    verbs: ["get", "list"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
