apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}-config
  labels:
    {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
data:
  operator.yaml: |-
    {{- with .Values.config }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
