apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}
  labels:
    {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "newrelic-infra-operator.appLabel" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "newrelic-infra-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "newrelic-infra-operator.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "newrelic-infra-operator.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: clusterName
          value: {{ include "newrelic-infra-operator.cluster" . }}
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic/newrelic-infra-operator/
        - name: tls-key-cert-pair
          mountPath: /tmp/k8s-webhook-server/serving-certs/
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 1
          periodSeconds: 1
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "newrelic-infra-operator.fullname" . }}-config
      - name: tls-key-cert-pair
        secret:
          secretName: {{ template "newrelic-infra-operator.fullname" . }}-admission
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      {{- if $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
