{{- $licenseKey := include "newrelic-infra-operator.licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "newrelic-infra-operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "newrelic-infra-operator.labels" . | indent 4 }}
type: Opaque
data:
  license: {{ $licenseKey | b64enc }}
{{- end }}
